# Generated by Django 5.2.8 on 2025-11-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emaill', models.EmailField(max_length=254, unique=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
