# Generated by Django 5.2.8 on 2025-11-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='emaill',
            new_name='email',
        ),
    ]
